### ISSUE TITLE
Possible error - 3rd Ed - Page 10

### ISSUE THREAD

**Issue by mzakariaCERN** [rasbt/python-machine-learning-book-3rd-edition#110]
5th row from the bottom
`
x^{(i)} \epsilon \mathbb{R}^{150 x 1}
`
I think it should be

`
x_{j} \epsilon \mathbb{R}^{150 x 1}
`

(I used https://www.codecogs.com/latex/eqneditor.php to check my latex)

**Comment by rasbt** [comment]
I agree with you. This was correct in the 2nd edition, weird that the layouters introduced this error here. Thanks for noting!

**Comment by rasbt** [comment]
added it to the errata: https://github.com/rasbt/python-machine-learning-book-3rd-edition/tree/master/errata
