### ISSUE TITLE
ch3，p56，“niter” parameter  missed

### ISSUE THREAD

**Issue by konfer** [rasbt/python-machine-learning-book-3rd-edition#114]
with the initialized of the Perceptron class , the book mentioned the parameter "n_iter", the i cannot found in the code, and the code of 2nd  has it. so i think it should be a issue
![QQ20200217-112213](https://user-images.githubusercontent.com/5566941/74621391-cb2e7900-5177-11ea-989f-641679ad9a16.png)
![QQ20200217-112200](https://user-images.githubusercontent.com/5566941/74621396-ce296980-5177-11ea-8412-f8bc9c014d20.png)

**Comment by rasbt** [comment]
Thanks for the note! You are right, I missed that part of the sentence during editing, and the `n_iter` parameter has been removed from sklearn in v 0.21. Just added it to the errata (https://github.com/rasbt/python-machine-learning-book-3rd-edition/blob/master/errata/README.md). Thanks!
