### ISSUE TITLE
possible error ch15_part1.ipynb

### ISSUE THREAD

**Issue by Lwhieldon** [rasbt/python-machine-learning-book-3rd-edition#139]
When running the Categorical Crossentropy losses funcytion (line 22), receive error below indicating that the shape of input parameters is incorrect:

ValueError                                Traceback (most recent call last)
<ipython-input-21-00635c56faf5> in <module>
     24 tf.print(
     25     'CCE (w Probas): {:.4f}'.format(
---> 26     cce_probas(y_true=[0, 0, 1], y_pred=probas)),
     27     '(w Logits): {:.4f}'.format(
     28     cce_logits(y_true=[0, 0, 1], y_pred=logits)))

C:\ProgramData\Anaconda3\lib\site-packages\tensorflow\python\keras\losses.py in __call__(self, y_true, y_pred, sample_weight)
    147     with K.name_scope(self._name_scope), graph_ctx:
    148       ag_call = autograph.tf_convert(self.call, ag_ctx.control_status_ctx())
--> 149       losses = ag_call(y_true, y_pred)
    150       return losses_utils.compute_weighted_loss(
    151           losses, sample_weight, reduction=self._get_reduction())

C:\ProgramData\Anaconda3\lib\site-packages\tensorflow\python\autograph\impl\api.py in wrapper(*args, **kwargs)
    253       try:
    254         with conversion_ctx:
--> 255           return converted_call(f, args, kwargs, options=options)
    256       except Exception as e:  # pylint:disable=broad-except
    257         if hasattr(e, 'ag_error_metadata'):

C:\ProgramData\Anaconda3\lib\site-packages\tensorflow\python\autograph\impl\api.py in converted_call(f, args, kwargs, caller_fn_scope, options)
    455   if conversion.is_in_whitelist_cache(f, options):
    456     logging.log(2, 'Whitelisted %s: from cache', f)
--> 457     return _call_unconverted(f, args, kwargs, options, False)
    458 
    459   if ag_ctx.control_status_ctx().status == ag_ctx.Status.DISABLED:

C:\ProgramData\Anaconda3\lib\site-packages\tensorflow\python\autograph\impl\api.py in _call_unconverted(f, args, kwargs, options, update_cache)
    337 
    338   if kwargs is not None:
--> 339     return f(*args, **kwargs)
    340   return f(*args)
    341 

C:\ProgramData\Anaconda3\lib\site-packages\tensorflow\python\keras\losses.py in call(self, y_true, y_pred)
    251           y_pred, y_true)
    252     ag_fn = autograph.tf_convert(self.fn, ag_ctx.control_status_ctx())
--> 253     return ag_fn(y_true, y_pred, **self._fn_kwargs)
    254 
    255   def get_config(self):

C:\ProgramData\Anaconda3\lib\site-packages\tensorflow\python\util\dispatch.py in wrapper(*args, **kwargs)
    199     """Call target, and fall back on dispatchers if there is a TypeError."""
    200     try:
--> 201       return target(*args, **kwargs)
    202     except (TypeError, ValueError):
    203       # Note: convert_to_eager_tensor currently raises a ValueError, not a

C:\ProgramData\Anaconda3\lib\site-packages\tensorflow\python\keras\losses.py in categorical_crossentropy(y_true, y_pred, from_logits, label_smoothing)
   1533   y_true = smart_cond.smart_cond(label_smoothing,
   1534                                  _smooth_labels, lambda: y_true)
-> 1535   return K.categorical_crossentropy(y_true, y_pred, from_logits=from_logits)
   1536 
   1537 

C:\ProgramData\Anaconda3\lib\site-packages\tensorflow\python\util\dispatch.py in wrapper(*args, **kwargs)
    199     """Call target, and fall back on dispatchers if there is a TypeError."""
    200     try:
--> 201       return target(*args, **kwargs)
    202     except (TypeError, ValueError):
    203       # Note: convert_to_eager_tensor currently raises a ValueError, not a

C:\ProgramData\Anaconda3\lib\site-packages\tensorflow\python\keras\backend.py in categorical_crossentropy(target, output, from_logits, axis)
   4685   output = ops.convert_to_tensor_v2(output)
   4686 
-> 4687   target.shape.assert_is_compatible_with(output.shape)
   4688   if from_logits:
   4689     return nn.softmax_cross_entropy_with_logits_v2(

C:\ProgramData\Anaconda3\lib\site-packages\tensorflow\python\framework\tensor_shape.py in assert_is_compatible_with(self, other)
   1132     """
   1133     if not self.is_compatible_with(other):
-> 1134       raise ValueError("Shapes %s and %s are incompatible" % (self, other))
   1135 
   1136   def most_specific_compatible_shape(self, other):

ValueError: Shapes (3,) and (1, 3) are incompatible
[ch15_part1.zip](https://github.com/rasbt/python-machine-learning-book-3rd-edition/files/5592817/ch15_part1.zip)

**Comment by rasbt** [comment]
Thanks for the note. @vmirly was double-checking the code and it looks like it's a Tf version issue. I.e., in newer TensorFlow versions,  the lines


```python
    tf.print(
         'CCE (w Probas): {:.4f}'.format(
         cce_probas(y_true=[0, 0, 1], y_pred=probas)),
         '(w Logits): {:.4f}'.format(
         cce_logits(y_true=[0, 0, 1], y_pred=logits)))
```

need to be changed to

```python
    tf.print(
         'CCE (w Probas): {:.4f}'.format(
         cce_probas(y_true=[[0, 0, 1]], y_pred=probas)),
         '(w Logits): {:.4f}'.format(
         cce_logits(y_true=[[0, 0, 1]], y_pred=logits)))
```

**Comment by Lwhieldon** [comment]
Nested lists get me every time!
