### ISSUE TITLE
NameError: name 'Perceptron' is not defined

### ISSUE THREAD

**Issue by daledet** [rasbt/python-machine-learning-book-3rd-edition#141]
NameError                                 Traceback (most recent call last)
<ipython-input-2-1f5cc16c9991> in <module>
----> 1 ppn = Perceptron(eta=0.1, n_iter=10)
      2 ppn.fit(X,y)
      3 plt.plot(range(1, len(ppn.errors_) + 1),
      4               ppn.errors_, marker='o')
      5 plt.xlabel('Epochs')

NameError: name 'Perceptron' is not defined

**Comment by rasbt** [comment]
Hi there,

in which chapter did you get the error?

**Comment by daledet** [comment]
Chapter 2

**Comment by daledet** [comment]
...Also from page 35, should the following code be nested under the function or in the for loop?

        plot_decision_regions(X, y, classifier=ppn)
        plt.xlabel('sepal length [cm]')
        plt.ylabel('petal length [cm]')
        plt.legend(loc='upper left')
        plt.show()

**Comment by rasbt** [comment]
Thanks. Should be defined on pg. 27. Maybe you accidentally skipped it.

<img width="595" alt="Screen Shot 2020-12-10 at 9 21 01 AM" src="https://user-images.githubusercontent.com/5618407/101791338-07e1ad00-3ac9-11eb-98b3-5cb60852ff15.png">

**Comment by daledet** [comment]
I have the Perceptron class in my code, but it is not working.

**Comment by rasbt** [comment]
Maybe there is a typo somewhere? When you use the code from https://github.com/rasbt/python-machine-learning-book-3rd-edition/tree/master/ch02 it works?
