### ISSUE TITLE
Plot chapter 2 not working

### ISSUE THREAD

**Issue by daledet** [rasbt/python-machine-learning-book-3rd-edition#142]
From Chapter 2 P.35 - Should the following code be nested under the function or under the for loop?

        plot_decision_regions(X, y, classifier=ppn)
        plt.xlabel('sepal length [cm]')
        plt.ylabel('petal length [cm]')
        plt.legend(loc='upper left')
        plt.show()

I have tried both, and the plot does not show up either way.

**Comment by rasbt** [comment]
> From Chapter 2 P.35 - Should the following code be nested under the function or under the for loop?

No, like you typed it should be fine. 

<img width="466" alt="Screen Shot 2020-12-10 at 9 22 27 AM" src="https://user-images.githubusercontent.com/5618407/101791532-3fe8f000-3ac9-11eb-84b3-f220adcafd62.png">


Can you check if something simple like

```python
import matplotlib.pyplot as plt

plt.show([1, 2], [3, 4])
```

shows the plot?

**Comment by daledet** [comment]
I just checked, and no that code is not showing a plot.

**Comment by rasbt** [comment]
That might be some general matplotlib configuration issue then. I recommend debugging that first. It will likely solve the other problem then

**Comment by daledet** [comment]
OK thanks.
With the other issue. I have the Perceptron class in my code, but it is not working.

**Comment by daledet** [comment]
None of this is working.
I hate Jupyter notebooks with every fiber of my being.

**Comment by rasbt** [comment]
1) 

Maybe you added the Percpetron class code but didn't execute it? 

If things get out of hand, I recommend restartign the notebook and executing all cells
<img width="375" alt="Screen Shot 2020-12-10 at 9 58 09 AM" src="https://user-images.githubusercontent.com/5618407/101796174-49288b80-3ace-11eb-8a15-159fdff4ba26.png">



2) 
If you are on older jupyter notebook and/or matpltotlib versions, adding and executing

%matplotlib inline 

in a cell on top of the notebook may help with showing the plots.

**Comment by daledet** [comment]
I deleted all, and will write the code in pure python instead.
Thank you for trying to help, but JN has never worked for me.

**Comment by daledet** [comment]
My word! Restart Kernal and Run All Cells is the elixir of life! It is the life force that fuels the dreams of champions!  
A decent nap followed by a strong cuppa joe is pretty helpful too. Thanks for guiding me past this first major JN hurdle!

**Comment by rasbt** [comment]
Nice. Glad it solved the issue
