### ISSUE TITLE
Issue with scatter plot in chap 3

### ISSUE THREAD

**Issue by austinofohio** [rasbt/python-machine-learning-book-3rd-edition#151]
I'm working with the code in chapter 3 in windows powershell and I can't get the code to run. I'm working with the first part of the code where we are plotting the three flower cases while training the perceptron.

I am getting this error:

![image](https://user-images.githubusercontent.com/84792775/119525525-9468ea80-bd4c-11eb-9226-1018f7c8653f.png)

Here's the version of numpy, Python, matplotlib, pandas, and sklearn that I have currently unstalled:

Python: 3.9.1 (tags/v3.9.1:1e5d33e, Dec  7 2020, 17:08:21) [MSC v.1927 64 bit (AMD64)]
numpy: 1.20.3
matplotlib: 3.4.2
pandas: 1.2.4
sklearn: 0.24.2

Please note that I am using the code provided on packt.com

**Comment by austinofohio** [comment]
I installed an older version of matplotlib, 3.3.0 and it worked. However I believe from versions 3.3.2 and on a explicit list will be needed in place of a string of single colors.

**Comment by rasbt** [comment]
Thanks for the note and looking into it! It seems that it is a matplotlib 3.4 issue indeed. Changing the `c` argument from

```python
        if LooseVersion(matplotlib.__version__) < LooseVersion('0.3.4'):
            plt.scatter(X_test[:, 0],
                        X_test[:, 1],
                        c='',
                        edgecolor='black',
                        alpha=1.0,
                        linewidth=1,
                        marker='o',
                        s=100, 
                        label='test set')
```

to

```python
            plt.scatter(X_test[:, 0],
                        X_test[:, 1],
                        c='none',
                        edgecolor='black',
                        alpha=1.0,
                        linewidth=1,
                        marker='o',
                        s=100, 
                        label='test set')        
```

fixes that. Updated it in the notebook.
