### ISSUE TITLE
Chapter 16 - tfds.feature.text module is deprecated.

### ISSUE THREAD

**Issue by Jeffresh** [rasbt/python-machine-learning-book-3rd-edition#155]
In page 587:  you use :
- ```tfds.feature.text.Tokenizer()``` but is deprecated. 
- For now you can use ```tokenizer = tfds.deprecated.text.Tokenizer()```
 instead. 

Dont know which is the new implementation.

**Comment by Jeffresh** [comment]
This happens in all the following code that use ```feature.text``` module and is solved using the ```deprecated``` statement. I try to find where this modules are moved,  but I can't find it. I find that now tensorflow has ```tensorflow_text module```, a dedicated module for preprocessing text, that you have to install separately, like dataset module, but the logic , method's names and use of them are changed a lil bit, so don't now the cost to migrate the code to use that.

**Comment by rasbt** [comment]
Thanks for the note! Just updated it so that it should work with newer tensorflow_dataset versions via 

```python
try:
    tokenizer = tfds.features.text.Tokenizer()
except AttributeError:
    tokenizer = tfds.deprecated.text.Tokenizer()
```
