### ISSUE TITLE
Definintion of  tokenizer in 8.3 Working with bigger data

### ISSUE THREAD

**Issue by niwak01** [rasbt/python-machine-learning-book-3rd-edition#160]
I think it should be modified as the comment below .

```python
def tokenizer(text):
    text = re.sub('<[^>]*>', '', text)
    #emoticons = re.findall('(?::|;|=)(?:-)?(?:\)|\(|D|P)', text.lower())                 # "text.lower()" should be "text"
    emoticons = re.findall('(?::|;|=)(?:-)?(?:\)|\(|D|P)', text)
    text = re.sub('[\W]+', ' ', text.lower()) +\
        ' '.join(emoticons).replace('-', '')
    tokenized = [w for w in text.split() if w not in stop]
    return tokenized
```

**Comment by rasbt** [comment]
Thanks for the suggestion!

Hm, I don't recall why I used `text.lower()` up there and wonder if there was a specific reason, or whether it's really unnecessary as you point out 🤔.

Doing a quick test, it seems like they both produce the same results. But yeah, maybe there was a special edge case that I had in mind. Hmm...

**Comment by niwak01** [comment]
Thank you very much for your response.

I think you might have intended to write as follows
  emoticons = re.findall('(?::|;|=)(?:-)?(?:\)|\(|**_d_**|**_p_**)', text.lower())
in order to find not only ':-P', but also ':-p)'

**Comment by rasbt** [comment]
Oh this makes absolute sense, thanks a lot! Changed it!
